### ISSUE TITLE
Metas de plantação

### ISSUE THREAD

**Issue by flaviopmarques** [GPMM/ControlHarvest#2]
A cada ciclo de tempo criar uma meta que o jogador deverá alcançar de colheita.
Estas metas terão um prazo para serem atingidas.

**Comment by joeldossantos** [comment]
Exemplo “vai ter feira no fim de semana, você precisa produzir 10kg de milho nos próximos 5min” - Isso deve evitar que o jogador fique muito tempo sem plantar só esperando os predadores acabarem com as pragas

**Comment by flaviopmarques** [comment]
feito.
