### ISSUE TITLE
Implementar migração de pragas

### ISSUE THREAD

**Issue by joeldossantos** [GPMM/ControlHarvest#37]
Ao invés de adicionar uma praga por vez, fazer a adição de um número aleatório entre 3 e 5, da mesma espécie, para migrar.

Fazer a migração somente quando a população de pragas de uma determinada espécie sumir por um tempo.

A migração pode ser feita também de acordo com o que está sendo plantado

**Comment by flaviopmarques** [comment]
Feito.

**Comment by flaviopmarques** [comment]
Feito.
