### ISSUE TITLE
Parametrizar valores de comportamento do jogo

### ISSUE THREAD

**Issue by joeldossantos** [GPMM/ControlHarvest#39]
Criar variáveis para guardar as escolhas de:
- percentual de energia abaixo do qual se alimenta
- velocidade de cada inseto
- números mínimos e máximos de insetos migrados
- tempo entre migração
- tempo entre estágios da planta
- ângulos de movimento dos insetos
- e por ai vai

**Comment by flaviopmarques** [comment]
feito.
