### ISSUE TITLE
Adicionar pragas após primeira colheita

### ISSUE THREAD

**Issue by joeldossantos** [GPMM/ControlHarvest#4]
Iniciar o jogo sem nenhuma praga, dando tempo para o jogador plantar e colher a primeira planta. A partir de então as pragas começam a aparecer.

**Comment by joeldossantos** [comment]
Pelo que percebi o primeiro inseto surge assim que se planta a primeira planta. A ideia seria ele aparecer somente depois que se colhe.

**Comment by flaviopmarques** [comment]
Feito.
